const { chromium } = require('playwright');
const sharp = require('sharp');
const fs = require('fs');
const path = require('path');
const { spawn } = require('child_process');
const OUT = process.argv[2] || '/tmp/subway-stage10-teacher';
const EPISODES = Number(process.env.STAGE10_TEACHER_EPISODES || 8);
const SECONDS = Number(process.env.STAGE10_TEACHER_SECONDS || 45);
const KEYS = {left:'ArrowLeft', right:'ArrowRight', jump:'ArrowUp', roll:'ArrowDown'};
const ACTIONS = ['stay','left','right','jump','roll'];
fs.mkdirSync(OUT,{recursive:true}); const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function decode(png,w=64,h=36){const {data}=await sharp(png).resize(w,h,{fit:'fill'}).removeAlpha().raw().toBuffer({resolveWithObject:true});const gray=new Float32Array(w*h),rgb=new Float32Array(w*h*3);for(let i=0,p=0;i<gray.length;i++,p+=3){const r=data[p]/255,g=data[p+1]/255,b=data[p+2]/255;rgb[p]=r;rgb[p+1]=g;rgb[p+2]=b;gray[i]=.299*r+.587*g+.114*b;}return {gray,rgb,w,h};}
function meanAbs(a,b){let s=0;for(let i=0;i<a.length;i++)s+=Math.abs(a[i]-b[i]);return s/a.length;}
function isDeath(img){const {rgb,w,h}=img;let green=0,lower=0,orange=0,total=w*h;for(let y=0;y<h;y++)for(let x=0;x<w;x++){const p=(y*w+x)*3,r=rgb[p],g=rgb[p+1],b=rgb[p+2];if(y>=h*.5){lower++;if(g>r*1.12&&g>b*1.25&&g>.38)green++;}if(r>.68&&g>.20&&g<.78&&b<.28)orange++;}return green/Math.max(1,lower)>.48&&orange/total>.10;}
function band(gray,w,h,prev,xa,xb,ya,yb){const x0=Math.floor(w*xa),x1=Math.floor(w*xb),y0=Math.floor(h*ya),y1=Math.floor(h*yb);let edge=0,temp=0,m=0,m2=0,c=0;for(let y=y0;y<y1-1;y++)for(let x=x0;x<x1-1;x++){const i=y*w+x,v=gray[i];edge+=Math.abs(v-gray[i+1])+Math.abs(v-gray[i+w]);if(prev)temp+=Math.abs(v-prev[i]);m+=v;m2+=v*v;c++;}edge/=2*Math.max(1,c);temp/=Math.max(1,c);m/=Math.max(1,c);m2/=Math.max(1,c);return edge*1.15+temp*.75+Math.sqrt(Math.max(0,m2-m*m))*.12;}
function profiles(gray,w,h,prev){return [[.12,.40],[.34,.66],[.60,.88]].map(([a,b])=>({upper:band(gray,w,h,prev,a,b,.38,.63),lower:band(gray,w,h,prev,a,b,.63,.90),full:band(gray,w,h,prev,a,b,.38,.90)}));}
function choose(p,lane){const cur=p[lane],opts=[];if(lane>0)opts.push({a:'left',gain:cur.full-p[lane-1].full});if(lane<2)opts.push({a:'right',gain:cur.full-p[lane+1].full});opts.sort((a,b)=>b.gain-a.gain);if(opts.length&&opts[0].gain>.020)return {action:opts[0].a,reason:'safer_adjacent_lane',confidence:Math.min(.99,.60+opts[0].gain*5)};const v=cur.lower-cur.upper;if(v>.012&&cur.lower>.070)return {action:'jump',reason:'lower_band_hazard',confidence:Math.min(.98,.58+v*5)};if(v<-.018&&cur.upper>.075)return {action:'roll',reason:'upper_band_hazard',confidence:Math.min(.98,.58-v*5)};if(opts.length&&opts[0].gain>.010)return {action:opts[0].a,reason:'marginal_safer_lane',confidence:.62};return {action:'stay',reason:'no_high_confidence_hazard',confidence:.72};}
async function focus(c){await c.evaluate(x=>{x.tabIndex=0;x.focus();});const b=await c.boundingBox();if(b)await c.click({position:{x:b.width/2,y:b.height/2},force:true}).catch(()=>{});} async function press(c,k){await c.press(k,{delay:180});}
async function openGame(context,id){const page=await context.newPage();page.on('console',m=>fs.appendFileSync(path.join(OUT,`${id}-console.log`),`[${m.type()}] ${m.text()}\n`));await page.goto('https://poki.com/en/g/subway-surfers',{waitUntil:'domcontentloaded',timeout:120000});let game=null,canvas=null,deadline=Date.now()+100000;while(Date.now()<deadline){game=page.frames().filter(f=>f.url().includes('.gdn.poki.com')).pop()||null;if(game){const c=game.locator('#pixi-canvas');if(await c.count().catch(()=>0)){canvas=c;break;}}await sleep(650);}if(!canvas)throw Error('official Pixi canvas not found');const webgl=await game.evaluate(()=>{const c=document.createElement('canvas'),gl=c.getContext('webgl',{stencil:true,failIfMajorPerformanceCaveat:true});if(!gl)return {ok:false};const e=gl.getExtension('WEBGL_debug_renderer_info');return {ok:true,stencil:gl.getParameter(gl.STENCIL_BITS),renderer:e?gl.getParameter(e.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER)};});if(!webgl.ok)throw Error('strict WebGL gate failed');await focus(canvas);return {page,game,canvas,webgl};}
async function activity(c){const xs=[];for(let i=0;i<7;i++){xs.push((await decode(await c.screenshot())).gray);if(i<6)await sleep(180);}const d=[];for(let i=1;i<xs.length;i++)d.push(meanAbs(xs[i-1],xs[i]));d.sort((a,b)=>a-b);return d[Math.floor(d.length/2)]>.003;}
async function startup(c){const seq=[['Space','Enter','Space','ArrowUp'],['Enter','Space','ArrowLeft','ArrowRight','ArrowUp'],['Space','ArrowUp','ArrowDown']];for(let r=0;r<10;r++){await focus(c);if(await activity(c))return true;for(const k of seq[r%seq.length]){await press(c,k);await sleep(300);}await sleep(650);}return false;}
function recorder(file){const d=process.env.DISPLAY;if(!d)throw Error('DISPLAY missing');return spawn('ffmpeg',['-y','-loglevel','warning','-f','x11grab','-draw_mouse','0','-framerate','30','-video_size','1280x720','-i',`${d}+0,0`,'-an','-c:v','libx264','-preset','ultrafast','-crf','22','-pix_fmt','yuv420p',file],{stdio:['pipe','inherit','inherit']});}
async function stopRec(p){if(!p||p.exitCode!==null)return;p.stdin.write('q\n');await Promise.race([new Promise(r=>p.once('exit',r)),sleep(5000)]);if(p.exitCode===null)p.kill('SIGINT');}
async function episode(browser,n){const id=`official_stage10_teacher_ep${String(n).padStart(2,'0')}`,context=await browser.newContext({viewport:{width:1280,height:720},locale:'en-US'});try{const g=await openGame(context,id);if(!(await startup(g.canvas)))return {episode_id:id,accepted:false,reason:'startup_failed'};const video=path.join(OUT,`${id}.mp4`),actionsPath=path.join(OUT,`${id}-actions.json`),rec=recorder(video);await sleep(700);const t0=Date.now();let prev=null,lane=1,dead=false,step=0;const decisions=[],counts=Object.fromEntries(ACTIONS.map(a=>[a,0]));while((Date.now()-t0)/1000<SECONDS){const img=await decode(await g.canvas.screenshot());if(isDeath(img)){dead=true;break;}const p=profiles(img.gray,img.w,img.h,prev),t=(Date.now()-t0)/1000,ch=choose(p,lane);decisions.push({episode_id:id,step,t_sec:+t.toFixed(4),action:ch.action,lane_estimate:lane,teacher_reason:ch.reason,teacher_confidence:+ch.confidence.toFixed(3),pixel_profiles:p.map(z=>({upper:+z.upper.toFixed(5),lower:+z.lower.toFixed(5),full:+z.full.toFixed(5)})),label_origin:'exact_browser_input_from_pixel_teacher',policy_input:'pixels_only'});counts[ch.action]++;if(ch.action!=='stay')await press(g.canvas,KEYS[ch.action]);if(ch.action==='left')lane=Math.max(0,lane-1);else if(ch.action==='right')lane=Math.min(2,lane+1);prev=img.gray;step++;await sleep(360);}const duration=(Date.now()-t0)/1000;await stopRec(rec);fs.writeFileSync(actionsPath,JSON.stringify({episode_id:id,duration_sec:+duration.toFixed(3),death_detected:dead,action_counts:counts,decisions},null,2));return {episode_id:id,accepted:duration>=22,duration_sec:+duration.toFixed(3),death_detected:dead,video_path:video,actions_path:actionsPath,action_counts:counts,webgl:g.webgl,provenance:{source:'official Subway Surfers on Poki',source_url:'https://poki.com/en/g/subway-surfers',capture:'self-generated exact actions from pixel-only teacher',reuse_status:'self_generated_for_research',exact_input_labels:true},policy_contract:'pixel-policy-contract-v1.1',teacher:'pixel-only lane/vertical hazard heuristic'};}finally{await context.close().catch(()=>{});}}
(async()=>{const browser=await chromium.launch({headless:false,args:['--enable-webgl','--ignore-gpu-blocklist','--use-gl=angle','--use-angle=gl','--disable-dev-shm-usage','--no-sandbox','--window-size=1280,720']});const eps=[];for(let i=1;i<=EPISODES;i++){try{eps.push(await episode(browser,i));}catch(e){eps.push({episode_id:`official_stage10_teacher_ep${String(i).padStart(2,'0')}`,accepted:false,reason:String(e.stack||e)});}}await browser.close();const good=eps.filter(e=>e.accepted),tot=Object.fromEntries(ACTIONS.map(a=>[a,good.reduce((s,e)=>s+(e.action_counts?.[a]||0),0)]));const out={stage:'10-pixel-teacher-exact-collection-v1',policy_contract:'pixel-policy-contract-v1.1',requested_episodes:EPISODES,accepted_episodes:good.length,total_action_counts:tot,teacher_uses_privileged_game_state:false,exact_key_logs_used_only_as_labels:true,episodes:eps};fs.writeFileSync(path.join(OUT,'stage10_teacher_summary.json'),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));if(good.length<6)process.exit(12);})().catch(e=>{console.error(e);process.exit(1)});